FROM jsonfry/android-sdk:bare
RUN echo y | android update sdk --no-ui --all --filter extra-android-support,extra-google-google_play_services,extra-android-m2repository,extra-google-m2repository,extra-google-play_apk_expansion,extra-google-play_billing,extra-google-play_licensing
