build:
  image: rancher/docker:1.9.1
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  commands:
  - docker login -e $DOCKER_EMAIL -p $DOCKER_PASSWORD -u $DOCKER_USERNAME
  - docker pull jsonfry/android-sdk:support
  - ./build-sdk.sh
